### PR TITLE
Readme formatting fix

### PR DESCRIPTION
**Pull request by vazhnov**
Is not finished yet.
Here will be more commits soon.

### CODE REVIEW

**Comment by vazhnov** [comment]
I don't know how to format normally a chapter after `sudo raspi-config`.
Also please check SQL commands.

**Comment by vazhnov** [comment]
@khinds10 , could you please take a look at this merge request?

**Comment by khinds10** [comment]
Cool! do you have the parts to make this project?  I have a new version on my desk now, but working too much to finish it, it's half put together :(   the GPS module with now 3 screens and a temp sensor + pi zero W

**Comment by vazhnov** [comment]
@khinds10 , I'm working on this setup: [SBC GNSS recorder with Bluetooth](https://wiki.openstreetmap.org/wiki/User:Vazhnov_Alexey/Record_GNSS_traces/Bluetooth_and_web_panel), and I want to add some beeper, screen and buttons.

**Pull request merged**
